MathDrinks/Controllers/ContactController.cs
using MathDrinks.Interfaces;
using MathDrinks.Models;
using Microsoft.AspNetCore.Mvc;

namespace MathDrinks.Controllers
{
    public class ContactController : Controller
    {
        public readonly IApplicationMySqlDbContext _db;

        public ContactController(IApplicationMySqlDbContext db)
        {
            _db = db;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Contact obj)
        {
            _db.Contact.Add(obj);
            _db.Save();
            TempData["success"] = "Contato enviado com sucesso.";
            return RedirectToAction("Create");
        }
    }
}

MathDrinks/Controllers/ProductController.cs
using MathDrinks.Interfaces;
using MathDrinks.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using OfficeOpenXml;

namespace MathDrinks.Controllers
{
    public class ProductController : Controller
    {
        private readonly IApplicationMySqlDbContext _db;
        private readonly IProducExcelService _excelService;

        public ProductController(
            IApplicationMySqlDbContext db,
            IProducExcelService excelService)
        {
            _db = db;
            _excelService = excelService;
        }

        public IActionResult GetProductId(int id)
        {
            var productFromDb = _db.Product.AsNoTracking().Where(c => c.Id == id).FirstOrDefault();
            return Ok( new { productFromDb?.Price, productFromDb?.Description });
        }

        public IActionResult GetAllProduct()
        {
            IEnumerable<Product> producsObj = _db.Product.ToList();
            return Ok(producsObj);
        }

        public async Task<IActionResult> Export()
        {
            IEnumerable<Product> products = _db.Product.ToList();
            await _excelService.ExportToExcel(products, "C:/ProjetosMateusPadraoMvc/MathDrinksWeb/MathDrinks/excel", "products");

            return Ok();
        }

        public IActionResult Index()
        {
            IEnumerable<Product> producsObj = _db.Product.ToList();
            return View(producsObj);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Product obj)
        {
            if (ModelState.IsValid)
              _db.Product.Add(obj);
            _db.Save();
            TempData["success"] = "Produto criado com sucesso.";
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var productFromDb = _db.Product.AsNoTracking().Where(c => c.Id == id).FirstOrDefault();
            if (productFromDb == null)
            {
                return NotFound();
            }
            return View(productFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Product obj)
        {
            if (ModelState.IsValid)
                _db.Product.Update(obj);
            _db.Save();
            TempData["success"] = "Produto editado com sucesso.";
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var productFromDb = _db.Product.AsNoTracking().Where(c => c.Id == id).FirstOrDefault();
            if (productFromDb == null)
            {
                return NotFound();
            }
            return View(productFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int? id)
        {
            var obj = _db.Product.AsNoTracking().Where(c => c.Id == id).FirstOrDefault();
            if (obj == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
                _db.Product.Remove(obj);
            _db.Save();
            TempData["success"] = "Produto deletado com sucesso.";
            return RedirectToAction("Index");
        }
    }
}

MathDrinks/Controllers/SupplierController.cs
using MathDrinks.Interfaces;
using MathDrinks.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MathDrinks.Controllers
{
    public class SupplierController : Controller
    {
        public readonly IApplicationMySqlDbContext _db;
                
        public SupplierController(IApplicationMySqlDbContext db)
        {
            _db = db;
        }

        public IActionResult GetSupplierId(int id)
        {
            var supplier = _db.Supplier.AsNoTracking().Where(c => c.Id == id).FirstOrDefault();
            return Ok(new { supplier?.Name });
        }

        public IActionResult Index()
        {
            IEnumerable<Supplier> objCategories = _db.Supplier.ToList();
            return View(objCategories);
        }

        public IActionResult Create() 
        {
            Fill();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Supplier obj)
        {
            //Validate(obj);
            _db.Supplier.Add(obj);
            _db.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            ///Está variavel auxiliar é pra instanciar as entidades produto e o supplier no supplier_product porque o include não estava instanciando
            ///produto
            var supplier_product = _db.Supplier_Product.AsNoTracking()
                .Where(c => c.SupplierId == id)
                .Include(sp => sp.supplier)
                .Include(sp => sp.product);
            ///pegando o fornecedor do banco de dados onde o id passado no construtor é igual ao id do fornecedor da tabela 
            var supplierFromDb = _db.Supplier.AsNoTracking().Where(c => c.Id == id).FirstOrDefault();
            ///supplierProduct instanciado e pronto para ser utilizado na tabela para mostrar no front end
            supplierFromDb.supplierProduct = supplier_product.ToList();

            if (supplierFromDb == null)
            {
                return NotFound();
            }
            return View(supplierFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Supplier obj)
        {
            _db.Supplier.Update(obj);
            _db.Save();
            TempData["success"] = "Fornecedor editado com sucesso.";
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var supplierFromDb = _db.Supplier.AsNoTracking().Where(c => c.Id == id).FirstOrDefault();

            if (supplierFromDb == null)
            {
                return NotFound();
            }
            return View(supplierFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int? id)
        {
            var obj = _db.Supplier.AsNoTracking().Where(c => c.Id == id).FirstOrDefault();
            if (ModelState.IsValid)
                _db.Supplier.Remove(obj);
            _db.Save();
            TempData["success"] = "Fornecedor deletado com sucesso.";
            return RedirectToAction("Index");
        }

        private void Fill() 
        {
        var products = _db.Product.AsNoTracking().ToList();
            ViewBag.Product = products.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name });
        }

        private void Validate(Supplier supplier)
        {
            if (String.IsNullOrEmpty(supplier.CNPJ) || supplier.CNPJ.Length != 18)
            {
                ModelState.AddModelError("CNPJ", "Insira um CNPJ válido.");
            }
        }
    }
}

MathDrinks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - MathDrinks</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/MathDrinks.styles.css" asp-append-version="true" />
        <link rel="stylesheet" href="~//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    </head>
    <body class="bg-light">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MathDrinks</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Produtos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Create">Contato</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Supplier" asp-action="Index">Fornecedores</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted bg-danger">
            <div class="container text-dark">
                &copy 2022 - MathDrinks <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/jquery/dist/main.js"></script>
        <script src="~/lib/jquery/dist/exportExcel.js"></script>
        <script src="~/lib/jquery/dist/updateTableProducts.js"></script>
        <script src="~/lib/jquery/dist/getInfoProducts.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

MathDrinks/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script> 
    <script type="text/javascript">
      toastr.success('@TempData["success"]');
    </script>
}
@if(TempData["error"] != null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script> 
    <script type="text/javascript">
      toastr.error('@TempData["error"]');
    </script>
}