MathDrinks/Models/Supplier.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace MathDrinks.Models
{
    public class Supplier
    {
        public int Id { get; set; } 

        [Column(TypeName = "varchar(35)")]
        public string Name { get; set; }
        
        [Column(TypeName = "varchar(35)")]
        public string FantasyName { get; set; }
       
        [Column(TypeName = "varchar(45)")]
        public string CNPJ { get; set; }
        
        [Column(TypeName = "varchar(35)")]
        public string Cep { get; set; }
        public string Created_by { get; set; } = "Administrador";

        [Column(TypeName = "datetime")]
        public DateTime Created_at { get; set; } = DateTime.Now;
        public string Updated_by { get; set; } = "Administrador";

        [Column(TypeName = "datetime")]
        public DateTime Updated_at { get; set; } = DateTime.Now;

        public List<Supplier_Product> supplierProduct { get; set; }
    }
}

MathDrinks/Controllers/SupplierController.cs
using MathDrinks.Interfaces;
using MathDrinks.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MathDrinks.Controllers
{
    public class SupplierController : Controller
    {
        public readonly IApplicationMySqlDbContext _db;
                
        public SupplierController(IApplicationMySqlDbContext db)
        {
            _db = db;
        }

        public IActionResult GetSupplierId(int id)
        {
            var supplier = _db.Supplier.AsNoTracking().Where(c => c.Id == id).FirstOrDefault();
            return Ok(new { supplier?.Name });
        }

        public IActionResult Index()
        {
            IEnumerable<Supplier> objCategories = _db.Supplier.ToList();
            return View(objCategories);
        }

        public IActionResult Create() 
        {
            Fill();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Supplier obj)
        {
            //Validate(obj);
            _db.Supplier.Add(obj);
            _db.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            ///Está variavel auxiliar é pra instanciar as entidades produto e o supplier no supplier_product porque o include não estava instanciando
            ///produto
            var supplier_product = _db.Supplier_Product.AsNoTracking()
                .Where(c => c.SupplierId == id)
                .Include(sp => sp.supplier)
                .Include(sp => sp.product);
            ///pegando o fornecedor do banco de dados onde o id passado no construtor é igual ao id do fornecedor da tabela 
            var supplierFromDb = _db.Supplier.AsNoTracking().Where(c => c.Id == id).FirstOrDefault();
            ///supplierProduct instanciado e pronto para ser utilizado na tabela para mostrar no front end
            supplierFromDb.supplierProduct = supplier_product.ToList();

            if (supplierFromDb == null)
            {
                return NotFound();
            }
            return View(supplierFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Supplier obj)
        {
            _db.Supplier.Update(obj);
            _db.Save();
            TempData["success"] = "Fornecedor editado com sucesso.";
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var supplierFromDb = _db.Supplier.AsNoTracking().Where(c => c.Id == id).FirstOrDefault();

            if (supplierFromDb == null)
            {
                return NotFound();
            }
            return View(supplierFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int? id)
        {
            var obj = _db.Supplier.AsNoTracking().Where(c => c.Id == id).FirstOrDefault();
            if (ModelState.IsValid)
                _db.Supplier.Remove(obj);
            _db.Save();
            TempData["success"] = "Fornecedor deletado com sucesso.";
            return RedirectToAction("Index");
        }

        private void Fill() 
        {
        var products = _db.Product.AsNoTracking().ToList();
            ViewBag.Product = products.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name });
        }

        private void Validate(Supplier supplier)
        {
            if (String.IsNullOrEmpty(supplier.CNPJ) || supplier.CNPJ.Length != 18)
            {
                ModelState.AddModelError("CNPJ", "Insira um CNPJ válido.");
            }
        }
    }
}

MathDrinks/Controllers/SupplierProductsController.cs
using MathDrinks.Interfaces;
using MathDrinks.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MathDrinks.Controllers
{
    public class SupplierProductsController : Controller
    {

        public readonly IApplicationMySqlDbContext _db;

        public SupplierProductsController(IApplicationMySqlDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Supplier_Product> objSupplierProduct = _db.Supplier_Product.ToList();
            return View(objSupplierProduct);
        }

        public IActionResult Create(int SupplierId)
        {
            Fill();
            var model = new Supplier_Product { SupplierId = SupplierId };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Supplier_Product obj)
        {
            _db.Supplier_Product.Add(obj);
            _db.Save();
            TempData["success"] = "Produto vinculado com sucesso.";
            return RedirectToAction("Index", "Supplier");
        }

        public IActionResult Edit(int id)
        {
            Fill();
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var supplierProducts = _db.Supplier_Product.AsNoTracking().Where(c => c.Id == id).FirstOrDefault();

            if (supplierProducts == null)
            {
                return NotFound();
            }
            return View(supplierProducts);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Supplier_Product obj)
        {
            _db.Supplier_Product.Update(obj);
            _db.Save();
            TempData["success"] = "Edição feita com sucesso.";
            return RedirectToAction("Index", "Supplier");
        }

        public IActionResult Delete(int id)
        {
            Fill();
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var supplierProductFromDb = _db.Supplier_Product.AsNoTracking().Where(c => c.Id == id).FirstOrDefault();
            if (supplierProductFromDb == null)
            {
                return NotFound();
            }
            return View(supplierProductFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int? id)
        {
            var obj = _db.Supplier_Product.AsNoTracking().Where(c => c.Id == id).FirstOrDefault();
            if (ModelState.IsValid)
            _db.Supplier_Product.Remove(obj);
            _db.Save();
            TempData["success"] = "Produto deletado do fornecedor.";
            return RedirectToAction("Index", "Supplier");
        }
 
        private void Fill()
        {
            var products = _db.Product.AsNoTracking().ToList();
            ViewBag.Product = products.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name });
        }
    }
}

MathDrinks/Views/Supplier/Create.cshtml
@model Supplier

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Criar Fornecedor</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name">Nome</label>
            <input asp-for="Name" required id="Name" placeholder="Digite o nome do fornecedor" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="FantasyName">Nome Fantasia</label>
            <input asp-for="FantasyName" required placeholder="Digite seu nome fantasia do fornecedor" class="form-control" />
            <span asp-validation-for="FantasyName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="CNPJ">CNPJ</label>
            <input asp-for="CNPJ" required placeholder="Digite o CNPJ do fornecedor" class="form-control" />
            <span asp-validation-for="CNPJ" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Cep" id="cep">Cep Do Fornecedor</label>
            <input asp-for="Cep" required placeholder="Cep do fornecedor" class="form-control" />
            <span asp-validation-for="Cep" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Criar</button>
        <a asp-controller="Supplier" asp-action="Index" class="btn btn-secondary" style="width:150px">Voltar a Lista</a>
    </div>
</form>

@section Scripts{
    @{
    <partial name="_Notification" />
    <partial name="_ValidationScriptsPartial" />
    }
}

MathDrinks/Views/Supplier/Delete.cshtml
@model Supplier
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Excluir Fornecedor</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name">Nome</label>
            <input asp-for="Name" disabled placeholder="Digite o nome do fornecedor" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="FantasyName">Nome Fantasia</label>
            <input asp-for="FantasyName" disabled placeholder="Digite seu nome fantasia do fornecedor" class="form-control" />
            <span asp-validation-for="FantasyName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="CNPJ">CNPJ</label>
            <input asp-for="CNPJ" disabled placeholder="Digite o CNPJ do fornecedor" class="form-control" />
            <span asp-validation-for="CNPJ" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Cep" id="cep">Cep Do Fornecedor</label>
            <input asp-for="Cep" disabled placeholder="Cep do fornecedor" class="form-control" />
            <span asp-validation-for="Cep" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Remover</button>
        <a asp-controller="Supplier" asp-action="Index" class="btn btn-secondary" style="width:150px">Voltar a Lista</a>
    </div>
</form>

@section Scripts{
    @{
    <partial name="_Notification" />
    <partial name="_ValidationScriptsPartial" />
    }
}

MathDrinks/Views/Supplier/Edit.cshtml
@model Supplier

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Editar Fornecedor</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name">Nome</label>
            <input asp-for="Name" placeholder="Digite o nome do fornecedor" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="FantasyName">Nome Fantasia</label>
            <input asp-for="FantasyName" placeholder="Digite seu nome fantasia do fornecedor" class="form-control" />
            <span asp-validation-for="FantasyName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="CNPJ">CNPJ</label>
            <input asp-for="CNPJ" placeholder="Digite o CNPJ do fornecedor" class="form-control" />
            <span asp-validation-for="CNPJ" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Cep" id="cep">Cep Do Fornecedor</label>
            <input asp-for="Cep" placeholder="Cep do fornecedor" class="form-control" />
            <span asp-validation-for="Cep" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Editar</button>
        <a asp-controller="Supplier" asp-action="Index" class="btn btn-secondary" style="width:150px">Voltar a Lista</a>
    </div>
</form>
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary text-danger">Lista de Produtos</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="SupplierProducts" asp-action="Create" asp-route-SupplierId="@Model.Id" id="botao-adicionar-produto" class="btn btn-primary bg-danger">
                <i class="bi bi-plus-circle"></i> &nbsp; Adicionar novo produto.
            </a>
        </div>
    </div>
    <br /><br />
    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Nome do Produto
                </th>
                <th>
                    Descrição
                </th>
                <th>
                    Preço
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in @Model.supplierProduct)
            {
                <tr>
                    <td width="30%">
                        @obj.product.Name
                    </td>
                    <td width="40%">
                        @obj.Drescription
                    </td>
                    <td width="30%">
                        @obj.Price
                    </td>
                    <td>
                        <div class="w-76 btn-group" role="group">
                            <a asp-controller="SupplierProducts" asp-action="Edit" asp-route-id="@obj.Id"
                           class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i> Editar</a>
                            <a asp-controller="SupplierProducts" asp-action="Delete" asp-route-id="@obj.Id"
                           class="btn btn-danger mx-2"><i class="bi bi-trash3"></i> Remove</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts{
    @{
    <partial name="_Notification" />
    <partial name="_ValidationScriptsPartial" />
    }
}

MathDrinks/Views/Supplier/Index.cshtml
@model IEnumerable<Supplier>
@{
    ViewData["Title"] = "Supplier Page";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary text-danger">Lista de Fornecedores</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Supplier" asp-action="Create" class="btn btn-primary bg-danger">
                <i class="bi bi-plus-circle"></i> &nbsp; Criar Novo Fornecedor
            </a>
        </div>
    </div>
    <br /><br />
    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Nome
                </th>
                <th>
                    CNPJ
                </th>
                <th>
                    Cep
                </th>
            </tr>

        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="25%">
                        @obj.FantasyName
                    </td>
                    <td width="25%">
                        @obj.CNPJ
                    </td>
                    <td width="25%">
                        @obj.Cep
                    </td>
                    <td>
                        <div class="w-76 btn-group" role="group">
                            <a asp-controller="Supplier" asp-action="Edit" asp-route-id="@obj.Id"
                           class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i> Editar</a>
                            <a asp-controller="Supplier" asp-action="Delete" asp-route-id="@obj.Id"
                           class="btn btn-danger mx-2"><i class="bi bi-trash3"></i> Remove</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>